
export const buildLotQuery = () => {
  return `
    id,
    code,
    variety_id,
    user_id,
    overridden,
    override_reason,
    overridden_by,
    qr_url,
    created_at,
    updated_at,
    plant_id,
    campaign_id,
    category_id,
    unit_id,
    lot_type_id,
    origin_lot_id,
    origin_text,
    calculated_label_id,
    final_label_id,
    pgo_override_reason,
    pgo_overridden_by,
    pgo_overridden_at,
    amount,
    variety:varieties(
      id,
      name,
      created_by,
      crop:crops(name)
    ),
    user:users(
      id,
      name,
      email
    ),
    plant:plants(
      id,
      name
    ),
    campaign:campaigns(
      id,
      name
    ),
    category:categories(
      id,
      name
    ),
    unit:units(
      id,
      name
    ),
    lot_type:lot_types(
      id,
      name
    ),
    origin_lot:lots(
      id,
      code,
      variety:varieties(
        id,
        name,
        crop:crops(name)
      )
    ),
    samples(
      id,
      user_id,
      test_ids,
      internal_code,
      status,
      sample_type_id,
      estimated_result_date,
      created_at,
      updated_at,
      test_results(
        id,
        parameter_id,
        value,
        created_at,
        parameter:parameters(
          id,
          name,
          type
        )
      )
    ),
    media(
      id,
      type,
      url,
      created_at,
      updated_at
    )
  `;
};
