// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyaayxcamgqzbmybbior.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5YWF5eGNhbWdxemJteWJiaW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MTE1NTEsImV4cCI6MjA2MzA4NzU1MX0.Zfv4wKo4wUgnRkHxssGAPGEnhp2GPEgmOEROQU4WEGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);